### ISSUE TITLE
signal  'finished'  and 'fail'

### ISSUE THREAD

**Issue by Alyavin** [htool/ESP32_Precision-9_compass_CMPS14#4]
Greetings friend! Thank you very much for your work! Please tell me if you plan to continue working on this project? I'm interested in the code about the readiness of the calibration and its failure!

**Comment by htool** [comment]
I just committed the 'calibration finished' bit, so you can find it there.

**Comment by Alyavin** [comment]
Hello, can you tell me the 'calibration failed' bit? You can do it here!
